"""This file was generated by xsdata, v26.2, on 2026-08-23 05:07:05

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.nfcom.bindings.v1_0.cons_sit_nfcom_tipos_basico_v1_00 import (
    TconsSitNfcom,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfcom"


@dataclass(kw_only=True)
class ConsSitNfcom(TconsSitNfcom):
    """
    Schema de validação XML dp Pedido de Consulta da Situação Atual da
    NFCom.
    """

    class Meta:
        name = "consSitNFCom"
        namespace = "http://www.portalfiscal.inf.br/nfcom"
