"""This file was generated by xsdata, v26.2, on 2026-08-23 05:07:05

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfcom"


class EvCancNfcomDescEvento(Enum):
    CANCELAMENTO = "Cancelamento"


@dataclass(kw_only=True)
class EvCancNfcom:
    """
    Schema XML de validação do evento do cancelamento 110111.

    :ivar descEvento: Descrição do Evento - “Cancelamento”
    :ivar nProt: Número do Protocolo de Status da NFCom
    :ivar xJust: Justificativa do Cancelamento
    """

    class Meta:
        name = "evCancNFCom"
        namespace = "http://www.portalfiscal.inf.br/nfcom"

    descEvento: EvCancNfcomDescEvento = field(
        metadata={
            "type": "Element",
            "white_space": "preserve",
        }
    )
    nProt: str = field(
        metadata={
            "type": "Element",
            "white_space": "preserve",
            "pattern": r"[0-9]{16}",
        }
    )
    xJust: str = field(
        metadata={
            "type": "Element",
            "min_length": 15,
            "max_length": 255,
            "white_space": "preserve",
            "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
        }
    )
