"""This file was generated by xsdata, v26.2, on 2026-08-23 05:36:43

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field

from nfelib import CommonMixin
from nfelib.nfcom.bindings.v1_0.tipos_geral_nfcom_v1_00 import (
    Tamb,
    TcorgaoIbge,
)
from nfelib.nfcom.bindings.v1_0.xmldsig_core_schema_v1_01 import Signature

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfcom"


@dataclass(kw_only=True)
class Tevento(CommonMixin):
    """
    Tipo Evento.
    """

    class Meta:
        name = "TEvento"

    infEvento: Tevento.InfEvento = field(
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
        }
    )
    signature: Signature = field(
        metadata={
            "name": "Signature",
            "type": "Element",
            "namespace": "http://www.w3.org/2000/09/xmldsig#",
        }
    )
    versao: str = field(
        metadata={
            "type": "Attribute",
            "white_space": "preserve",
            "pattern": r"1\.00",
        }
    )

    @dataclass(kw_only=True)
    class InfEvento:
        """
        :ivar cOrgao: Código do órgão de recepção do Evento.
        :ivar tpAmb: Identificação do Ambiente: 1 - Produção 2 -
            Homologação
        :ivar CNPJ: CNPJ do emissor do evento
        :ivar chNFCom: Chave de Acesso da NFCom vinculada ao evento
        :ivar dhEvento: Data e Hora do Evento, formato UTC (AAAA-MM-
            DDThh:mm:ssTZD)
        :ivar tpEvento: Tipo do Evento
        :ivar nSeqEvento: Seqüencial do evento para o mesmo tipo de
            evento.  Para maioria dos eventos será 1, nos casos em que
            possa existir mais de um evento o autor do evento deve
            numerar de forma seqüencial.
        :ivar detEvento: Detalhamento do evento específico
        :ivar Id: Identificador da TAG a ser assinada, a regra de
            formação do Id é: “ID” + tpEvento +  chave da NFCom +
            nSeqEvento (preencher com zeros a esquerda para compor 3
            digitos)
        """

        cOrgao: TcorgaoIbge = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
            }
        )
        tpAmb: Tamb = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
            }
        )
        CNPJ: str = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "white_space": "preserve",
                "pattern": r"[A-Z0-9]{12}[0-9]{2}",
            }
        )
        chNFCom: str = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "max_length": 44,
                "white_space": "preserve",
                "pattern": r"[0-9]{6}[A-Z0-9]{12}[0-9]{26}",
            }
        )
        dhEvento: str = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "white_space": "preserve",
                "pattern": r"(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00))",
            }
        )
        tpEvento: str = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "white_space": "preserve",
                "pattern": r"[0-9]{6}",
            }
        )
        nSeqEvento: str = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "white_space": "preserve",
                "pattern": r"[0-9]{1,3}",
            }
        )
        detEvento: Tevento.InfEvento.DetEvento = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
            }
        )
        Id: str = field(
            metadata={
                "type": "Attribute",
                "pattern": r"ID[0-9]{12}[A-Z0-9]{12}[0-9]{28}|ID[0-9]{12}[A-Z0-9]{12}[0-9]{29}",
            }
        )

        @dataclass(kw_only=True)
        class DetEvento:
            """
            :ivar any_element: XML do evento Insira neste local o XML
                específico do tipo de evento (cancelamento,
                encerramento, registro de passagem).
            :ivar versaoEvento:
            """

            any_element: None | object = field(
                default=None,
                metadata={
                    "type": "Wildcard",
                    "namespace": "##any",
                    "process_contents": "skip",
                },
            )
            versaoEvento: str = field(
                metadata={
                    "type": "Attribute",
                    "white_space": "preserve",
                    "pattern": r"1\.(0[0-9]|[1-9][0-9])",
                }
            )


@dataclass(kw_only=True)
class TretEvento:
    """
    Tipo retorno do Evento.
    """

    class Meta:
        name = "TRetEvento"

    infEvento: TretEvento.InfEvento = field(
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
        }
    )
    signature: None | Signature = field(
        default=None,
        metadata={
            "name": "Signature",
            "type": "Element",
            "namespace": "http://www.w3.org/2000/09/xmldsig#",
        },
    )
    versao: str = field(
        metadata={
            "type": "Attribute",
            "white_space": "preserve",
            "pattern": r"1\.00",
        }
    )

    @dataclass(kw_only=True)
    class InfEvento:
        """
        :ivar tpAmb: Identificação do Ambiente: 1 - Produção 2 -
            Homologação
        :ivar verAplic: Versão do Aplicativo que recebeu o Evento
        :ivar cOrgao: Código do órgão de recepção do Evento. Utilizar a
            Tabela do IBGE extendida, utilizar 90 para identificar
            SUFRAMA
        :ivar cStat: Código do status da registro do Evento
        :ivar xMotivo: Descrição literal do status do registro do Evento
        :ivar chNFCom: Chave de Acesso NFCom vinculada
        :ivar tpEvento: Tipo do Evento vinculado
        :ivar xEvento: Descrição do Evento
        :ivar nSeqEvento: Seqüencial do evento
        :ivar dhRegEvento: Data e Hora de do recebimento do evento ou do
            registro do evento formato AAAA-MM-DDThh:mm:ssTZD
        :ivar nProt: Número do protocolo de registro do evento
        :ivar Id:
        """

        tpAmb: Tamb = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
            }
        )
        verAplic: str = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "min_length": 1,
                "max_length": 20,
                "white_space": "preserve",
                "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
            }
        )
        cOrgao: TcorgaoIbge = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
            }
        )
        cStat: str = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "white_space": "preserve",
                "pattern": r"[0-9]{3,4}",
            }
        )
        xMotivo: str = field(
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "min_length": 1,
                "max_length": 255,
                "white_space": "preserve",
                "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
            }
        )
        chNFCom: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "max_length": 44,
                "white_space": "preserve",
                "pattern": r"[0-9]{6}[A-Z0-9]{12}[0-9]{26}",
            },
        )
        tpEvento: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "white_space": "preserve",
                "pattern": r"[0-9]{6}",
            },
        )
        xEvento: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "min_length": 4,
                "max_length": 60,
                "white_space": "preserve",
                "pattern": r"[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}",
            },
        )
        nSeqEvento: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "white_space": "preserve",
                "pattern": r"[0-9]{1,3}",
            },
        )
        dhRegEvento: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "white_space": "preserve",
                "pattern": r"(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00))",
            },
        )
        nProt: None | str = field(
            default=None,
            metadata={
                "type": "Element",
                "namespace": "http://www.portalfiscal.inf.br/nfcom",
                "white_space": "preserve",
                "pattern": r"[0-9]{16}",
            },
        )
        Id: None | str = field(
            default=None,
            metadata={
                "type": "Attribute",
                "pattern": r"ID[0-9]{16}",
            },
        )


@dataclass(kw_only=True)
class TprocEvento:
    """
    Tipo procEvento.

    :ivar eventoNFCom:
    :ivar retEventoNFCom:
    :ivar versao:
    :ivar ipTransmissor: IP do transmissor do documento fiscal para o
        ambiente autorizador
    :ivar nPortaCon: Porta de origem utilizada na conexão (De 0 a 65535)
    :ivar dhConexao: Data e Hora da Conexão de Origem
    """

    class Meta:
        name = "TProcEvento"

    eventoNFCom: Tevento = field(
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
        }
    )
    retEventoNFCom: TretEvento = field(
        metadata={
            "type": "Element",
            "namespace": "http://www.portalfiscal.inf.br/nfcom",
        }
    )
    versao: str = field(
        metadata={
            "type": "Attribute",
            "white_space": "preserve",
            "pattern": r"1\.00",
        }
    )
    ipTransmissor: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "white_space": "preserve",
            "pattern": r"(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])",
        },
    )
    nPortaCon: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "pattern": r"[0-9]{1,5}",
        },
    )
    dhConexao: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "white_space": "preserve",
            "pattern": r"(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00))",
        },
    )
