"""This file was generated by xsdata, v26.2, on 2026-08-23 05:36:43

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.nfcom.bindings.v1_0.evento_nfcom_tipos_basico_v1_00 import Tevento

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfcom"


@dataclass(kw_only=True)
class EventoNfcom(Tevento):
    """
    Schema XML de validação do Pedido de Registro de Evento da NFCom.
    """

    class Meta:
        name = "eventoNFCom"
        namespace = "http://www.portalfiscal.inf.br/nfcom"
