"""This file was generated by xsdata, v26.2, on 2026-08-23 05:07:05

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass

from nfelib.nfcom.bindings.v1_0.evento_nfcom_tipos_basico_v1_00 import (
    TretEvento,
)

__NAMESPACE__ = "http://www.portalfiscal.inf.br/nfcom"


@dataclass(kw_only=True)
class RetEventoNfcom(TretEvento):
    """
    Schema XML de validação do retorno Pedido de Evento da NFCom.
    """

    class Meta:
        name = "retEventoNFCom"
        namespace = "http://www.portalfiscal.inf.br/nfcom"
